version: "3.7"

services:
  app:
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
      target: dev
    container_name: app
    restart: always
    volumes:
      - .:/usr/src/app:rw,cached
