version: "3.7"

x-common:
  &default-common
  restart: always

services:
  app:
    <<: *default-common
    build:
      dockerfile: ./docker/Dockerfile
      context: .
      target: build
    container_name: app
    volumes:
      - .:/usr/src/app:rw,cached